#define ID_DIALDLG                  100
#define ID_MIDPOINT                 101
#define ID_DISABLED                 103
#define ID_VISIBLE                  104
#define ID_GROUP                    105
#define ID_TABSTOP                  106
#define ID_NOBUTTON                 107
#define ID_NONUMBER                 108
#define ID_NOTEXT                   109
#define ID_POINTSELECT              110
#define ID_PROPORTIONALTICKS        111
#define ID_360                      114
#define ID_RESET                    102
